export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS'

export const GET_MENUS_SUCCESS = 'GET_MENUS_SUCCESS'

export const TEST = 'TEST'

export const QUFU_STATUS_SUCCESS = 'QUFU_STATUS_SUCCESS'

export const GET_GAME_INFO_SUCCESS = 'GET_GAME_INFO_SUCCESS'

export const GET_FIRST_LEVEL_MENU = 'GET_FIRST_LEVEL_MENU'

export const GET_SERVER_DASHBOARD_SUCCESS = 'GET_SERVER_DASHBOARD_SUCCESS'